/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.mrchii.ai.sms;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int black=0x7f050003;
        public static final int dark_slate=0x7f050001;
        public static final int primary_green=0x7f050000;
        public static final int white=0x7f050002;
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f060000;
        public static final int activity_vertical_margin=0x7f060001;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
        public static final int ic_launcher_background=0x7f020001;
        public static final int ic_launcher_foreground=0x7f020002;
    }
    public static final class id {
        public static final int btnClearLogs=0x7f09000e;
        public static final int btnCloseNativeView=0x7f090002;
        public static final int btnGrantPermissions=0x7f09000a;
        public static final int btnOpenAppSettings=0x7f09000b;
        public static final int btnRefreshLogs=0x7f09000d;
        public static final int btnSaveUrl=0x7f090008;
        public static final int btnSetDefaultSms=0x7f090009;
        public static final int etBackendUrl=0x7f090007;
        public static final int nativeContainer=0x7f090001;
        public static final int rvSmsLogs=0x7f090010;
        public static final int switchAndroidSms=0x7f090006;
        public static final int switchAutoReply=0x7f090005;
        public static final int switchEmergencyStop=0x7f090004;
        public static final int tvEmptyLogs=0x7f090011;
        public static final int tvMessage=0x7f090015;
        public static final int tvMonitorPipelineStatus=0x7f09000f;
        public static final int tvRestrictedNotice=0x7f09000c;
        public static final int tvSender=0x7f090013;
        public static final int tvStatus=0x7f090003;
        public static final int tvTag=0x7f090012;
        public static final int tvTimestamp=0x7f090014;
        public static final int webView=0x7f090000;
    }
    public static final class layout {
        public static final int activity_main=0x7f040000;
        public static final int item_sms_log=0x7f040001;
    }
    public static final class mipmap {
        public static final int ic_launcher=0x7f030000;
        public static final int ic_launcher_round=0x7f030001;
    }
    public static final class string {
        public static final int android_sms_pipeline=0x7f070006;
        public static final int app_name=0x7f070000;
        public static final int app_subtitle=0x7f070002;
        public static final int app_title=0x7f070001;
        public static final int auto_reply_master=0x7f070005;
        public static final int backend_url_hint=0x7f070008;
        public static final int backend_url_label=0x7f070007;
        public static final int btn_clear_logs=0x7f070010;
        public static final int btn_grant_permissions=0x7f07000b;
        public static final int btn_open_app_settings=0x7f07000c;
        public static final int btn_refresh_logs=0x7f07000f;
        public static final int btn_save_url=0x7f070009;
        public static final int btn_set_default_sms=0x7f07000a;
        public static final int empty_logs_text=0x7f070011;
        public static final int infinix_restricted_notice=0x7f07000d;
        public static final int monitor_title=0x7f07000e;
        public static final int status_active=0x7f070003;
        public static final int stop_kill_switch=0x7f070004;
    }
    public static final class style {
        public static final int Theme_MrChiiAI=0x7f080000;
    }
}
